#!/bin/env bash
echo
echo "------------------------------------------------------------"
echo "                   Pulling from Git repo                    "
echo "------------------------------------------------------------"
echo
git fetch --all
git reset --hard origin/main
chmod +x ./helpers/captureframe.sh ./helpers/framegenerator.sh ./PiSecure ./stop
echo
echo "------------------------------------------------------------"
echo "                  Running main script file                  "
echo "------------------------------------------------------------"
echo
echo "Loading. . ."
python "./helpers/botInterface.py" &
python PiSecure.py
