#!/bin/env bash

echo "------------------------------------------------------------"
echo "                   Pulling from Git repo                    "
echo "------------------------------------------------------------"
git fetch --all
git reset --hard origin/main
chmod +x captureframe.sh framegenerator.sh PiSecure
echo ""
echo "------------------------------------------------------------"
echo "                  Running main script file                  "
echo "------------------------------------------------------------"

python PiSecure.py
